<?php
//模块名称
$name='User';
//模块中文名称
$title='用户中心';
//模块描述
$description='ThinkGms官网提供用户中心，基于AmazeUI.';
//模块版本
$version='1.0.1';
//作者
$author='管侯杰';
//作者主页
$author_site='http://guanblog.sinaapp.com/';
//作者邮箱
$author_email='912524639@qq.com';
//是否允许配置
$is_config=0;
//配置（序列化数组）
$config='';
//依赖模块
$rely_module=array();
//依赖插件
$rely_addons=array();